site/en/guides/build/commissioning.md
site/en/guides/build/features/child-supervision.md
site/en/guides/build/features/inform-previous-parent-on-reattach.md
site/en/guides/build/features/jam-detection.md
site/en/guides/build/features/periodic-parent-search.md
site/en/guides/build/index.md
site/en/guides/build/logs.md
site/en/guides/porting/implement-advanced-features.md
site/en/guides/porting/implement-platform-abstraction-layer-apis.md

A bunch of links were broken on GitHub (but are working on openthread.io after import).  Any links to existing docs on GitHub are now relative with .md filenames.

[guides] fix broken links

---

site/en/guides/thread-primer/ipv6-addressing.md

We had to adjust our openthread.io Copybara import to account for some new code block variations, which ended up conflicting with this one existing example in the Thread Primer.  So I've rewritten them here so that it's no longer an issue.
This is not a problem in the Chinese version of the Thread Primer since it's formatted slightly different (it doesn't have a period directly after the ending code tag), so that is unchanged.

Fix placeholder formatting in Thread Primer

---

site/en/codelabs/silabs-openthread-hardware/index.lab.md

Some metadata was missing.  Without it, the codelab doesn't appear in the Nest category of the Codelabs index: https://codelabs.developers.google.com/?cat=nest

Update SiLabs codelab metadata

---

site/en/guides/build/features/inform-previous-parent-on-reattach.md

See the implementation https://github.com/openthread/openthread/blob/05fd1deb497451464ff050102d8f2994e53e6820/src/core/thread/mle.cpp#L4004

[features] correct the destination of `InformPreviousParent` message

---

site/en/codelabs/openthread-border-router/index.lab.md

[codelabs] fix type on `thread start` command

---

site/en/codelabs/openthread-border-router-ipv6-multicast/index.lab.md
site/en/codelabs/openthread-hardware/index.lab.md

[codelabs] update hw codelabs to always use USB instead of UART

---

site/en/guides/_toc.yaml
site/en/guides/border-router/_toc.yaml

Need to add the _toc.yaml files from openthread.io so they can be updated here as content is added/removed.

Add TOCs for guides and border-router directories

---

site/en/codelabs/openthread-apis/index.lab.md
site/en/codelabs/openthread-border-router-ipv6-multicast/index.lab.md
site/en/codelabs/openthread-border-router/index.lab.md
site/en/codelabs/openthread-hardware/index.lab.md
site/en/codelabs/openthread-network-simulator/index.lab.md
site/en/codelabs/openthread-simulation-posix/index.lab.md
site/en/codelabs/openthread-simulation/index.lab.md
site/en/codelabs/openthread-testing-visualization/index.lab.md
site/en/codelabs/silabs-openthread-hardware/index.lab.md

Adding _project.yaml and _book.yaml metadata entries to each of the codelabs, required by developers.google.com

Adding Google metadata

---

site/en/guides/border-router/beaglebone-black.md

This is to address the changes in this PR: https://github.com/openthread/ot-br-posix/pull/1145
With these changes most of the setup done outside the normal scripts is redundant. The Wi-Fi setup is left as optional because network manager is now optional.

BBB remove redundant configurations and mark the Wi-Fi AP setup as optional

---

site/en/codelabs/openthread-apis/index.lab.md
site/en/codelabs/openthread-border-router-ipv6-multicast/index.lab.md
site/en/codelabs/openthread-border-router/index.lab.md
site/en/codelabs/openthread-hardware/index.lab.md
site/en/codelabs/openthread-network-simulator/index.lab.md
site/en/codelabs/openthread-simulation-posix/index.lab.md
site/en/codelabs/openthread-simulation/index.lab.md
site/en/codelabs/openthread-testing-visualization/index.lab.md
site/en/codelabs/silabs-openthread-hardware/index.lab.md

Metadata sections were missing the requires double linefeed immediately before the closing line

Corrected syntax error in metadata section of codelab files

---

site/en/codelabs/openthread-simulation/index.lab.md

Partially addressing issue #68 and making more explicit the terminal to use in the final steps of Section 5, _Manage the network with OpenThread Daemon_.

[codelabs] clarify terminal usage in OpenThread simulation

---

site/en/codelabs/openthread-border-router-ipv6-multicast/index.lab.md

Ping @wgtdkp, that was the source of the link to the Google docs.

Use public documentation in referenced docs

---

site/en/codelabs/openthread-hardware/index.lab.md

- Changed initial mentions of screen to 'GNU screen'
- Added `--verify` flag to `nrfjprog` invocation
- Clarified the mention of `wpantund`, providing some context
- Corrected path of `ot-ctl` binary
- Miscellaneous corrections

Build network w nordic codelab

---

README.md

updated README 
- removed reference to openthread-users Google Group
- removed reference to StackOverflow
- added reference to new Github OT discussion area

In support of change to GitHub Discussion

---

site/en/guides/border-router/external-commissioning/prepare.md

The default passphrase in the Web frontend is `j01Nme`. Use the same in the example.

Use the commonly used passphrase

---

site/en/codelabs/openthread-simulation-posix/index.lab.md

Both approach to quitting ot-ctl, either using **Ctrl+D** or `exit` command, will not lead to termination of ot-daemon.

[codelabs] fix the approach to quitting `ot-ctl`

---

site/en/codelabs/openthread-simulation/index.lab.md

The button 'Download Docker' links to the docker hub instead of the page to download docker.
Although the Docker hub link does point to various installation methods, https://www.docker.com/get-started/ seems a better starting point.

Update Docker link

---

site/en/guides/border-router/docker/test-connectivity.md

This PR updates the instruction for pinging an IPv4 address. After [updating the default NAT64 service to be openthread](https://github.com/openthread/ot-br-posix/pull/1539), users will be able to ping an IPv4 address directly.

update the instruction for pinging an IPv4 address

---

site/en/guides/_toc.yaml
site/en/guides/index.md

The update only happened on openthread.io when it should have happened here first.

Update guide index and menu for NAT64 codelab

---

site/en/reference/cli/contribute.md

In support of https://github.com/openthread/openthread/pull/8921

[cli] add guidance for multi-line cparam tags

---

site/en/guides/border-router/web-gui.md

As raised in the recent User feedback report, the TCP/IP port used by the WebGUI is not mentioned.

Explicitly state the TCP/IP port used by the WebGUI (80).

---

site/en/codelabs/openthread-border-router-nat64/index.lab.md
site/en/guides/border-router/external-commissioning/join.md

As discussed in https://github.com/openthread/ot-br-posix/issues/1858, here are a couple of improvements to the documentation in regards to NAT64.
Namely
- Added a note in the NAT64 colab that the well-known prefix is not supported and custom implementations will need to make use of `otNat64SynthesizeIp6Address()`.
- Removed a mention of the well-known prefix in another guide and added a link to the NAT64 colab.

Improve NAT64 documentation

---

site/en/guides/border-router/espressif-esp32.md

ESP releases the first version of `esp-thread-br`, so we want to update the instruction of the `Set up Repositories`.

Update Espressif border router code version

---

site/en/guides/border-router/_toc.yaml

When we imported the Android Border Router guide from AOSP to openthread.io, I manually changed the border router _toc.yaml there so we could publish it.  Since the source of that file is here on ot-docs, need to update this too so it doesn't get overwritten on a future Copybara run.

Update Border Router _toc.yaml with Android guide

---

site/en/guides/porting/index.md

This commit adds the 802.15.4-2015 requirement because some partners are not aware of it.

Update requirement for 802.15.4-2015 for Thread 1.2+

---

site/en/codelabs/openthread-network-simulator/index.lab.md

This adds info about the minimum Go and Python versions that are required. Because these components can't always be automatically installed, manual install may be needed and therefore the codelab needs to explain that. Also includes a few minor fixes/clarifications.
Close #181

[codelabs][otns] add info on minimum Go and Python versions

---

site/en/guides/build/index.md

openthread/examples/README.md was removed when 2023, this docs would lead other to a 404 file. So it needs to be changed as the newest cmake file.
[openthread/examples/README.md](https://github.com/openthread/openthread/blob/main/examples/README.md):
https://github.com/openthread/openthread/blob/main/etc/cmake/options.cmake:

 [ot-docs] replace a 404 file: Change 404 file `openthread/examples/README.md` to `openthread/etc/cmake/options.cmake`
